# Generated by Django 6.0.7 on 2026-07-31 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_momo', 'MTN Mobile Money'), ('carte_bancaire', 'Carte bancaire'), ('especes', 'Espèces (guichet)')], max_length=20)),
                ('reference_transaction', models.CharField(blank=True, max_length=100)),
                ('numero_telephone', models.CharField(blank=True, max_length=20)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=9)),
                ('statut', models.CharField(choices=[('initie', 'Initié'), ('reussi', 'Réussi'), ('echoue', 'Échoué')], default='initie', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('payload_brut', models.JSONField(blank=True, null=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='reservations.reservation')),
            ],
        ),
    ]
