# Generated by Django 6.0.7 on 2026-08-11 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeFidelite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_aller_simple_valides', models.PositiveIntegerField(default=0)),
                ('nb_aller_retour_valides', models.PositiveIntegerField(default=0)),
                ('credits_aller_simple', models.PositiveIntegerField(default=0)),
                ('credits_aller_retour', models.PositiveIntegerField(default=0)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fidelite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_alphanumerique', models.CharField(editable=False, max_length=10, unique=True)),
                ('qr_token', models.CharField(blank=True, editable=False, max_length=32)),
                ('type_billet', models.CharField(choices=[('aller_simple', 'Aller simple'), ('aller_retour', 'Aller-retour')], default='aller_simple', max_length=15)),
                ('client_nom_guichet', models.CharField(blank=True, max_length=100)),
                ('client_prenom_guichet', models.CharField(blank=True, max_length=100)),
                ('client_telephone_guichet', models.CharField(blank=True, max_length=20)),
                ('canal', models.CharField(choices=[('en_ligne', 'En ligne'), ('guichet', 'Guichet')], max_length=10)),
                ('statut', models.CharField(choices=[('en_attente_paiement', 'En attente de paiement'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('expiree', 'Expirée')], default='en_attente_paiement', max_length=25)),
                ('montant_total', models.DecimalField(decimal_places=0, default=0, max_digits=9)),
                ('est_recompense_fidelite', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('embarque', models.BooleanField(default=False)),
                ('date_embarquement', models.DateTimeField(blank=True, null=True)),
                ('agent_guichet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='accounts.agent')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('reservation_aller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations_retour', to='reservations.reservation')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='catalogue.voyage')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Passager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('siege', models.CharField(max_length=5)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passagers', to='reservations.reservation')),
            ],
            options={
                'unique_together': {('reservation', 'siege')},
            },
        ),
    ]
