# Generated by Django 6.0.7 on 2026-08-11 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('ordre_affichage', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre_affichage'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=80, unique=True)),
                ('region', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['ville'],
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('capacite', models.PositiveSmallIntegerField()),
                ('plan_sieges', models.JSONField()),
                ('actif', models.BooleanField(default=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bus', to='catalogue.classe')),
            ],
            options={
                'ordering': ['immatriculation'],
            },
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree_estimee', models.DurationField()),
                ('distance_km', models.PositiveIntegerField(blank=True, null=True)),
                ('arrivee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trajets_arrivee', to='catalogue.destination')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trajets_depart', to='catalogue.destination')),
            ],
            options={
                'ordering': ['depart__ville', 'arrivee__ville'],
                'unique_together': {('depart', 'arrivee')},
            },
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure_depart', models.DateTimeField()),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='planifie', max_length=15)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voyages', to='catalogue.bus')),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voyages', to='catalogue.trajet')),
            ],
            options={
                'ordering': ['date_heure_depart'],
            },
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_adulte', models.DecimalField(decimal_places=0, max_digits=8)),
                ('prix_enfant', models.DecimalField(decimal_places=0, max_digits=8)),
                ('voyage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tarif', to='catalogue.voyage')),
            ],
        ),
    ]
