# Generated by Django 6.0.7 on 2026-08-17 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraireRecurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_depart', models.TimeField()),
                ('prix_adulte', models.DecimalField(decimal_places=0, max_digits=8)),
                ('prix_enfant', models.DecimalField(decimal_places=0, max_digits=8)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires_recurrents', to='catalogue.classe')),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires_recurrents', to='catalogue.trajet')),
            ],
            options={
                'ordering': ['trajet', 'heure_depart'],
                'unique_together': {('trajet', 'classe', 'heure_depart')},
            },
        ),
        migrations.AddField(
            model_name='voyage',
            name='horaire_recurrent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voyages', to='catalogue.horairerecurrent'),
        ),
        migrations.AlterUniqueTogether(
            name='voyage',
            unique_together={('horaire_recurrent', 'date_heure_depart')},
        ),
    ]
